name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
    # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sofyan
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Checkout out code in the Go module directory
      uses: actions/checkout@v2

    - name: Run migrations
      uses: make migrateup

    - name: Test
      run: make test